name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7 # or the version you need
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecomm_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Start backend service
        run: |
          nohup java -jar target/product-management-0.0.1-SNAPSHOT.war & sleep 30

      - name: Run Tests
        run: mvn test -Dtest.port=8080
